#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

cat /etc/s6-overlay/s6-rc.d/init-adduser/branding

echo '
───────────────────────────────────────
GID/UID
───────────────────────────────────────'
echo "
User UID:    $(id -u abc)
User GID:    $(id -g abc)
───────────────────────────────────────
"

time32="$(date +%Y)"

if [[ "${time32}" == "1970" || "${time32}" == "1969" ]] && [ "$(uname -m)" == "armv7l" ]; then
    echo '
╔═════════════════════════════════════════════════════════════════════════════╗
║                                                                             ║
║        Your Docker Host is running an outdated version of libseccomp        ║
║                                                                             ║
║    To fix this, please visit https://docs.linuxserver.io/faq#libseccomp     ║
║                                                                             ║
║                 Apps will not behave correctly without this                 ║
║                                                                             ║
╚═════════════════════════════════════════════════════════════════════════════╝
'
    sleep infinity
fi

lsiown abc:abc /app
lsiown abc:abc /config
lsiown abc:abc /defaults
